### ISSUE TITLE
CRUD - PHP notice / bad index when submitted

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1010]
When CRUD is submitted, the following PHP notice is shown:
```
<b>Notice</b>:  Undefined offset: 0 in <b>.../vendor/atk4/ui/src/jsCallback.php</b> on line <b>144</b><br />
```

It seems that:
a) the `$response` is an array with one value but instead of with index `0`, the index is `1`
b) adding extra test if the index `0` exists seems to fix this issue

Questions:
a) What does the `0` index mean?
b) what is the purpose of the extra code when index `0` is presented?

How to fix this?

**Comment by ibelar** [comment]
This problem is associated with form submit having more than one hook to deal with and come from Hook refactoring.

https://github.com/atk4/core/blob/188895e63e2a30458a142e2b5d5e3f4751f69ffb/src/HookTrait.php#L175

For example:
```php
$form = \atk4\ui\Form::addTo($tab);
$form->addField('email');
$form->addField('checkbox', ['CheckBox']);
$form->addField('checkbox_', ['CheckBox']);

$form->onSubmit(function ($form) {
    // implement subscribe here
    $m = new \atk4\ui\Message('Error executing ', 'red');
    $m->init();
    $m->text->content = ('test');
    return $m;
});
````
When form is submitted, each CheckBox has added a 'loadPost' hook. Thus, when hook are executing, the response from `$response = $this->hook('submit');` is not correctly indexed. Because submit hook is the third one to execute, it will have an index of 2.

On the other side, jsCallback return is expected to receive a response with a 0 base index in order to check if a View object is return by form::onSubmit and act accordingly.

There are different way to tackle this problem but my question to @mvorisek is: 
Do we need to return an index response array in HookTrait::hook method?
````
 $return[$index] = call_user_func_array(
                            $data[0],
                            array_merge(
                                [$this],
                                $args,
                                $data[1]
                            )
                        );
````

if so, then we should check the response in Form::ajaxSubmit() method and re-index response properly.
something like:
````
                $response = $this->hook('submit');
                if (is_array($response)) {
                    $response = array_values($response);
                }
````

**Comment by mvorisek** [comment]
I have already analysed the impact of the hook refactoring already, but thanks, need help with fixing it - see https://github.com/atk4/ui/issues/986 . It makes sense to return the hook values indexes by the hook index that produced it.

To this issue: do we have a guarantee that the hook from which the result is used in `jsCallback` is always the first called? I think no, as if later a different hook with lower priority is added, it is called first.

> On the other side, jsCallback return is expected to receive a response with a 0 base index in order to check if a View object is return by form::onSubmit and act accordingly.

So do we want to use the value of first evaluated hook here of value of some specific hook - if value of some specific hook, then we should store the registration hook index and then use the value undex this index.

**Comment by ibelar** [comment]
To my knowledge, only jsCallback checked for index 0 response, and I believe this was done for directly returning a View object from a form submit. So it can be easily fixed in Form::ajaxSubmit() or maybe even better in jsCallback directly. 

Question for @romaninsh and @DarkSide666 - Is there other places in atk4 repo that uses response with index 0, other than jsCallback? 

If no, then I can issue a fix for this.

**Comment by DarkSide666** [comment]
Sorry, no idea about that :)
