### ISSUE TITLE
Refactor form->success() to rely on Message class

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#102]
Blocked by #101 

currently it's a hard-coded template, but we should be able to use a Message class.

**Comment by DarkSide666** [comment]
do you want to remove current functionality (form-success.html template) completely or just add additional functionality to be able to call:
$form->success(new \atk4\ui\Message('qwerty'));
or call it like $form->success('qwerty', 'sub-qwerty');, but render by using Message class (which will not be completely possible because currently we have header/message structure, but Message class only supports one text not two and no header there)

**Comment by romaninsh** [comment]
remove the current template. Here is reference code:

https://github.com/atk4/ui/blob/e4c13011e3e528ac6142e7e1e169daae77a2b0a6/src/Form.php#L292

``` php
        $success = new Message([$str, 'id'=>false, 'type'=>'success', 'icon'=>'check']);
        $success->app = $this->app;
        $success->init();
        $success->text->addParagraph($sub_header);
```

**Comment by romaninsh** [comment]
Blocked by #101

**Comment by mvorisek** [comment]
Closing as stale.
