### ISSUE TITLE
Order of object declarations has repercussions on javascript callback

### ISSUE THREAD

**Issue by TheNetworkIsDown** [atk4/ui#1164]
The following works:
```
$app = new myApp;
$m = new mTest($app->db);

$table = $app->add(new \atk4\ui\Table);
$table->setModel($m);

$vp = $app->add(new \atk4\ui\VirtualPage);
$form = $vp->add(new \atk4\ui\Form);
$form->setModel($m);

$button = $app->add(['Button', ['Add Item', 'icon'=>'plus']]);
$button->on('click', new \atk4\ui\jsModal('JSModal Title', $vp));

$form->onSubmit(function($form) use($table) {
  $form->model->save();
  return [
    $table->jsReload(),
    $form->success('ok'),
  ];
});
```

Whereas this does not work:
```
$app = new myApp;
$m = new mTest($app->db);

$vp = $app->add(new \atk4\ui\VirtualPage);
$form = $vp->add(new \atk4\ui\Form);
$form->setModel($m);

$table = $app->add(new \atk4\ui\Table);
$table->setModel($m);

$button = $app->add(['Button', ['Add Item', 'icon'=>'plus']]);
$button->on('click', new \atk4\ui\jsModal('JSModal Title', $vp));

$form->onSubmit(function($form) use($table) {
  $form->model->save();
  return [
    $table->jsReload(),
    $form->success('ok'),
  ];
});
```

Note the only thing that changes between the two is the order of declaration:
1) table first
2) vp+form first

"Does not work" here means: Instead of reloading the table, submitting the form seems to reload the modal. First the form's success message shortly pops up and then an empty form is displayed inside a modal.

Like that it is for example not possible to show the "Add" button above the table, because
* the button must follow the vp+form declaration
* the table must be the first to be declared, for whatever reason

Expected behavior: the order of declaration really should not matter here. I'd be inclined to label this as "first impression"...

**Comment by DarkSide666** [comment]
Not sure if it's related to your issue, but better use model object clones for setModel() otherwise you add **same** model object ($m) for table and for form and this can lead to some strange behavior.

**Comment by TheNetworkIsDown** [comment]
Thanks for the advice!

I've tried the following as a variant of non-working case 2 but it doesn't change anything
```
$app = new myApp;

$vp = $app->add(new \atk4\ui\VirtualPage);
$form = $vp->add(new \atk4\ui\Form);
$form->setModel(new mTest($app->db));

$table = $app->add(new \atk4\ui\Table);
$table->setModel(new mTest($app->db));

$button = $app->add(['Button', ['Add Item', 'icon'=>'plus']]);
$button->on('click', new \atk4\ui\jsModal('JSModal Title', $vp));

$form->onSubmit(function($form) use($table) {
  $form->model->save();
  return [
    $table->jsReload(),
    $form->success('ok'),
  ];
});
```

**Comment by ibelar** [comment]
As of now, this behavior is normal and it all has to do on how elements are rendered.

Here is what happening when you ask for table reload in solution # 2 when saving form:

The virtual page is added to the app before the table;
 - This means that the VirtualPage is rendered first in the render tree,
 - Then, the VirtualPage set function is called while rendering; 
 - Since the virtual page callback is still triggered, the app terminates and sends the output using the VirtualPage content, not the table content.

While using solution # 1 when saving form:
 - This means that the table is rendered first in the rendered tree;
 - Then the table reload is catch while rendering;
 - This terminate app execution by sending the Table content;

In order to keep your solution # 2, you would need to manually detect table reload, via a get argument, and avoid adding the VirtualPage during the reload. 

Hope this helps!

**Comment by TheNetworkIsDown** [comment]
Hmm, I must admit I don't exactly understand why reloading $table would instead try to reload $vp. Did I do something wrong here? Is using a Virtualpage maybe the wrong approach?

I am not referencing $vp for the reload, I specifically ask $table to be reloaded. So that is exactly what I am expecting to happen...

**Comment by ibelar** [comment]
> I am not referencing $vp for the reload, I specifically ask $table to be reloaded. So that is exactly what I am expecting to happen...

Understand that, and there is nothing wrong about that. It is just the way the framework is built and how VirtualPage and reload work. You add View to your app, then when all is added, the rendering process starts for each View, using the order in which they where added. While rendering, if a reload is catch, the rendering process stops and only render what was asked to be reloaded. But since VirtualPage is special, when asked to be rendered and it gets triggered, then rendering stop and only render the VirtualPage content.

Here are some alternative:

## Using VirtualPage

Use VirtualPage set function, so it forces you to put things in order:

````
$table = $app->add(new \atk4\ui\Table());
$table->setModel($m);

$vp = $app->add(new \atk4\ui\VirtualPage());
$vp->set(function($p) use ($table, $m) {
    $form = $p->add(new \atk4\ui\Form);
    $form->setModel(clone $m);
    $form->onSubmit(function($form) use($table) {
        $form->model->save();
        return [
            $table->jsReload(),
            $form->success('ok'),
        ];
    });
});

$button = $app->add(['Button', ['Add Item', 'icon'=>'plus']]);
$button->on('click', new \atk4\ui\jsModal('JSModal Title', $vp));
````

## Using Modal

Very similar to VirtualPage with jsModal but give you more control over the look of it.
see Modal class for all the options.

````
$table = $app->add(new \atk4\ui\Table);
$table->setModel($m);

$modal = $app->add(new \atk4\ui\Modal());
$modal->set(function ($p) use($m, $table) {
    $form = $p->add(new \atk4\ui\Form);
    $form->setModel(clone $m);
    $form->onSubmit(function($form) use($table) {
        $form->model->save();
        return [
            $table->jsReload(),
            $form->success('ok'),
        ];
    });
});

$button = $app->add(['Button', ['Add Item', 'icon'=>'plus']]);
$button->on('click', $modal->show());
````

**Comment by mvorisek** [comment]
Closing as explained/solved by @ibelar. If something needs to be changed, describe exactly what and propose a good solution.
