### ISSUE TITLE
AdminLayout is not working anymore with release 2.1

### ISSUE THREAD

**Issue by karakal** [atk4/ui#1300]
After upgrading to ui 2.1.0 no applications of mine are working anymore because of a missing function called addToWithCIUnsafe in View.php

![grafik](https://user-images.githubusercontent.com/2448293/84923927-2e99ca80-b0c8-11ea-9051-c266983db3cb.png)

I also tried with a complete new project, I cleared the cache of the composer and still the critical error with the missing function persists.

**Comment by mvorisek** [comment]
@romaninsh @DarkSide666 do all other releases as discussed to prevents these issues!

**Comment by DarkSide666** [comment]
All repos will be released in next few days. Still need to push some things in there before releasing.

**Comment by mvorisek** [comment]
@DarkSide666 @romaninsh But anyone using it now can not install it. Why not to simply do the releases now and then in a few days again?

**Comment by karakal** [comment]
But isn't this an internal problem of the ui-Project? Because Menu, View and Admin-Layout are all classes of ui?

How is this working in the demo?

**Comment by mvorisek** [comment]
@karakal no

**Comment by domainoverflow** [comment]
Having problems in all my atk4/ui based systems too :-(

**Comment by mvorisek** [comment]
Waiting for @romaninsh and @DarkSide666 to release all atk4 repos at once.

You can now require version `<2.0.999` in your `composer.json` file for all atk4 repos to fix this issue immediately.

Locking this conversation as the bug is known.

**Comment by romaninsh** [comment]
[edit] 

**Thanks for reporting this issue.**

**Yes this was INTERNAL ISSUE of ATK4/UI, our release process for 2.1 managed to scoop some extra PRs that depended on 2.2 features.**

Those have been now reverted and `2.1.2` was released. Simply run `composer update`.

**Comment by romaninsh** [comment]
@domainoverflow I have just released 2.1.1 of atk4/ui to address this. Could you run `composer update` and try again?

**Comment by domainoverflow** [comment]
Thanks @romaninsh  - I will try it right now and let you know shortly.

**Comment by domainoverflow** [comment]
Also, I did not point fingers. As I said, this is understandable. The only thing I complained was that the issue was closed twice without explanation. I also have offered to help multiple times -never got an answer. I think you guys do a fantastic job and I tried my best not to come across unpolite. Again, I spent a total of 9 days trying to fix it on my own, _**without bothering anyone here**_, so your understanding is also appreciated.  I will let you know if the new one worked. Thank you for your help.

**Comment by romaninsh** [comment]
@domainoverflow oh no - there was nothing wrong from your end! You noticed the issues and reported, thank you for this. I'm looking for some extra issues here:

https://github.com/atk4/ui/commits/release/2.1

Will update you when it looks more or less stable.

**Comment by romaninsh** [comment]
@domainoverflow , ok everything seems to be OK now - could you test your code in the evening and close this issue if fixed?

**Comment by domainoverflow** [comment]
thanks!!

**Comment by domainoverflow** [comment]
ok will try now

**Comment by domainoverflow** [comment]
Ok, @romaninsh , I tried 2.1.1

-PHP Fatal error:  Declaration of User::init() must be compatible with atk4\\data\\Model::init():
Which I fixed by adding :void to init when extending atk4 data model.

Then the next error showed up:

-Error : Class 'atk4\data\Persistence_SQL' not found 
Which I fixed by doing:
$this->db = new \atk4\data\Persistence_SQL 
TO
$this->db = new \atk4\data\Persistence\SQL

And then this one happened: 
-Error : Class 'Admin' not found 
Which I fixed by doing .  $this->initLayout(new \atk4\ui\Layout\Admin())  ( instead of 'Admin' )

- Error : Cannot use object of type User as array 
 $this->user = new User($this->db); -which works everywhere 

Which I fixed by
From:  $this->db = new \atk4\data\Persistence\SQL('pgsql:host=sld.tld;port=x;dbname=yvr','postgres','YUUYX'); ) 
TO 
        $this->db = new \atk4\data\Persistence\SQL('pgsql:host=sld.ca;port=x;dbname=fc;user=x; password=x');

and then 

Error : Class 'Centered' not found 

and it goes on and on .. 

I see now you have released 2.1.2 - so I will try again with 2.1.2 and report back. 

thanks for your help.

**Comment by domainoverflow** [comment]
Results with 2.1.2 @romaninsh .. 
Firstly, it could not find 'Centered' nor 'Admin' ( which I fixed by using initLayout(new \atk4\ui\Layout\Centered() and Admin() ) 
And now I get 
Error: Class 'View' not found
![ScreenshotATK4-2-1-2](https://user-images.githubusercontent.com/33677898/85303881-ee3ba300-b45f-11ea-819f-3c20868fe34b.jpg)

For when trying $seg = $app->add(['View', 'ui' => 'segment']); 
View.php is vendor/

I'm really stuck at this point. 
Thanks for your help, it is appreciated.

**Comment by ibelar** [comment]
> For when trying $seg = $app->add(['View', 'ui' => 'segment']);

@domainoverflow - Try using this syntax:

```
$app->add([\atk4\ui\View::class, 'ui' => 'segment']);
```

**Comment by domainoverflow** [comment]
Hi @ibelar 
Thank You for your help. 
Yeah, I see that I could do that .. but my problem is that I have literally hundreds of .phps using that format. 
Does that mean 2.1 and over will not support the previous syntax ? 
Thanks!!

**Comment by ibelar** [comment]
Yes! I know, it is additional work but it is for the better in the long term. You can use these regex pattern, supply by @mvorisek - to help you with the transition.

You will find them here: https://github.com/atk4/ui/pull/1158

**Comment by domainoverflow** [comment]
Thanks for letting me know @ibelar ... 
It's a lot of additional work in my case as I have lots of dynamic-generated flows but I guess too bad for me. :-(
Merci!
ps: and it doesn't take long to break further. For example, if I replace the 'View' and 'Form' with classes, it goes further but: 

-Error : Cannot use object of type atk4\ui\Misc\ProxyModel as array 

Is there a document or a list of what has been broken ? it looks like it is more than just the class syntax ?!

![atk4e-2](https://user-images.githubusercontent.com/33677898/85320982-c7d63180-b478-11ea-8b9e-d2e59b2d0aaf.png)

**Comment by georgehristov** [comment]
@domainoverflow the $view->add([View::class]) syntax is still supported but using `addTo` facilitates code completion and refactoring.
The Model array access has been deprecated in benefit of using `Model::get` / `Model::set` methods instead. You can still "activate" array access by using the `ModelArrayAccessTrait` in your models.

BC breaks are listed on top of the change log of the release. See https://github.com/atk4/data/releases or https://github.com/atk4/ui/releases for instance

**Comment by karakal** [comment]
> 
> -Error : Cannot use object of type atk4\ui\Misc\ProxyModel as array
> 
> Is there a document or a list of what has been broken ? it looks like it is more than just the class syntax ?!
> 
> ![atk4e-2](https://user-images.githubusercontent.com/33677898/85320982-c7d63180-b478-11ea-8b9e-d2e59b2d0aaf.png)

You also have to check all your access of models like $case['number'] is not working anymore, you have to use $case->get('number') and you can't use $case['number']=5 anymore but $case->set('number',5)

I just have "corrected" all my code for a project, only to realize that somehow Console is broken and not working anymore...

All the plugins (Login, Mastercrud,...) where not checked either... Somehow that is really frustrating...

**Comment by domainoverflow** [comment]
Yes, I am having a hard time too. I still have 5 projects to convert and have bumped into even more stuff ( seed usage has changed, lots of errors using seeds that worked before ) and I was wondering if a thread could be created so we could ask conversion problems ... instead of opening 200 .phps ..  I wonder, is someone willing to take question in order to help everyone out converting their code to the new code ?  PS: A section 'Deprecation & Syntax' in the online documentation ( changelog is very volumous ). The only place I found references was here: https://forum.agiletoolkit.org/t/atk-ui-2-1-release/834 
Thank you very much for any help !
ps: I read you are having problems with hosting the demo. If it helps, I could sponsor your hosting ( I can provide AWS instances as a way of giving back ). Let me know if it helps. I just want to convert my projects !!

**Comment by domainoverflow** [comment]
Thank you @karakal and @georgehristov  ... that was really helpful really ! I'm still struggling but you have shed a huge light on it, I wish these things were part of the latest readthedocs, anyhow thank you for your help and have an excellent week.
I wonder if any of you had success of the plugin components ? ( I am battling filestore, invoice, login and mastercrud ). thanks !
