### ISSUE TITLE
Centered layout scrolls slides over top of the screen:

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#138]
When centered page has too much content, in recent browser content goes off-screen (on the top) and is impossible to scroll to it:

http://ui.agiletoolkit.org/demos/header.php?layout=Centered

**Comment by DarkSide666** [comment]
Problem is because of `height:100%` style of main container.

So here are two cases and probably should be two separate layouts:
* CenteredFrame - center horizontally and vertically (like it is now). This layout is meant for small dialog frames which we actually want to show in the middle of viewport/screen.
* CenteredPage - center horizontally, but not vertically (like it is now, but without height:100% style). This layout is meant for horizontally centered pages.

**Comment by mayack** [comment]
![image](https://user-images.githubusercontent.com/540261/27508386-a993c9ba-58e3-11e7-96b8-e93df0b34239.png)

This DOM element should use 'min-height' property instead of 'height'.  This will resolve the problem.
