### ISSUE TITLE
Field names missing in Model->getField, causing corrupt Exception message

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1704]
In recent develop, example `demos/form/form2.php` don't work:
- First form can never be saved, as iso ~cannot be empty, nor~ cannot it be changed
- If you deactivate all validation handling in onSubmit to make it work again, still it will throw an error `Javascript Error
Syntax error, unrecognized expression: #`

The second form throws error `Atk4\Ui\Exception: Callback requested, but never reached. You may be missing some arguments in request URL.` on save.

**Comment by mvorisek** [comment]
I have already seen `Javascript Error Syntax error, unrecognized expression: #` somewhere during other issue debugging, this is definitely a bug that must be fixed.

**Comment by mvorisek** [comment]
@ibelar can you please look at the JS issue? It seems something is not escaped properly or deescaped/evaluated twice.

**Comment by mkrecek234** [comment]
More background @ibelar : For me I get the `Javascript Error Syntax error, unrecognized expression: #` always when saving a form which is placed in a Modal Virtual Page. Help appreciated as this is a major new bug

**Comment by mvorisek** [comment]
@mkrecek234 can you identify which atk4/ui commit started producing this issue?

**Comment by ibelar** [comment]
This is likely du to Data\Field error and badly formatted ValidationException throw when `Field::$name `is equal to null and has nothing to do with javascript.

see: https://github.com/atk4/data/blob/develop/src/Field.php#L282

Perhaps a regular exception should be thrown when $name property is null.

Otherwise the ValidationException will try to execute this javascript expression :
` $("#atk_layout_maestro_form").form("add prompt","","Must not be null")`

Which end up in showing the error message above because of the missing field name.

@mkrecek234 : Thanks for pointing out the error form2.php error. I will issue a fix for it. When you see this error, please check for Exception within your model.

**Comment by mvorisek** [comment]
iso cannot be empty because of the model definition

the main issue is the JS escaping

**Comment by mkrecek234** [comment]
@ibelar By removing the form->save() in the sample form2.php you circumvent this bug. There is an issue saving the form. We should keep real form-> save samples in our demos to demonstrate (and also have real life tests). Can you please check? In fact, this is a new bug that came with the last develop updates.

**Comment by mkrecek234** [comment]
@mvorisek @ibelar I found the reason for my issue: The `Javascript Error Syntax error, unrecognized expression: #` actually is caused in my case by a thrown Exception in the ` protected function _typecastSaveField(Field $field, $value)`in Persistence.php at https://github.com/atk4/data/blob/975b27f4de756118860da069ffff103633cc7f3a/src/Persistence.php#L271

The Exception however is not properly shown, but then the above Javascript Error is shown only. Can you check how to make sure that thrown Exception are properly displayed and not with the unrecognized expressions?

**Comment by ibelar** [comment]
The error message shown in form2.php happen because there is an exception thrown during the validation process.
this [line](https://github.com/atk4/ui/blob/d4be0d5b4c5108edf182e0d4b0b41bdadf583243/demos/init-db.php#L168) in init-db:       `  $c = $this->getModel()->tryLoadBy($this->fieldName()->name, $this->name);` is throwing an Exception.

This Exception is later caught within `Form::onSubmit()`  method, which generate a Fomantic form('add prompt') message:

```
    public function onSubmit(\Closure $callback)
    {
        $this->onHook(self::HOOK_SUBMIT, $callback);

        $this->cb->set(function () {
            try {
                $this->loadPost();
                $response = $this->hook(self::HOOK_SUBMIT);

                if (!$response) {
                    if (!$this->model instanceof \Atk4\Ui\Misc\ProxyModel) {
                        $this->model->save();

                        return $this->success('Form data has been saved');
                    }

                    return new JsExpression('console.log([])', ['Form submission is not handled']);
                }

                return $response;
            } catch (\Atk4\Data\ValidationException $val) {
                $response = [];
                foreach ($val->errors as $field => $error) {
                    $response[] = $this->error($field, $error);
                }

                return $response;
            }
        });

        return $this;
    }
```

What is happening is that $val->errors does not contains any field name, thus generating a bad Fomantic add prompt instruction using an empty field name. The add prompt generated is: ` $("#atk_layout_maestro_form").form("add prompt", "", "Must not be null")` 

When running this instruction return by the server, Fomantic throw an exception, because of badly formatted add prompt message, which is catch by apiService and display within a modal.

This error has nothing to do with Javascript, it simply catch a badly formatted add prompt message.

I think to correctly fix this, there should be a distinction between a real validation exception and an regular exception throw within the validate method. And I think this should be resolve on the Atk4\Data side. @mvorisek 
what do you think?

**Comment by mvorisek** [comment]
we have to throw an exception uniformly with other validation exceptions, not sure what you mean exactly, please submit a PR if you think something behave wrongly

**Comment by mkrecek234** [comment]
@mvorisek @ibelar I investigated this further. The issue indeed is that the field name is empty for all fields (short_name though is set) coming from this function: https://github.com/atk4/data/blob/975b27f4de756118860da069ffff103633cc7f3a/src/Persistence.php#L159

With the missing name though, any validation failure will also miss the field name, which ultimately creates the JsExpression error. @mvorisek may be you have an idea how to correct the `$field = $model->getField($fieldName);` to fill also the name in the array?

**Comment by mvorisek** [comment]
@mkrecek234 thanks for envestigation, let me know which array, eg. what do you expect exactly on which line, I think I can help quickly then ;-)

**Comment by mkrecek234** [comment]
@mvorisek on the line under the link above, `$row` still has complete field elements with `name` in it.
The command `$field = $model->getField($fieldName)` then returns an array which has `name` empty, but some other like `short_name` are there. So if you adjust `getField` to fill the array including the name, it should be alright.

**Comment by mvorisek** [comment]
I belive only short_name should be used and all other names should ideally throw an exception (we can unset easily, then it will emit an undefined warning due special trait from atk4/core) :)

**Comment by mkrecek234** [comment]
Your take @mvorisek - the missing name leads to 
```catch (\Atk4\Data\ValidationException $e) {
                $response = [];
                foreach ($val->errors as $field => $error) {
...```

be rendered with $field being empty.
