### ISSUE TITLE
Lookup control writes 0 instead of NULL for nullable field

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1813]
- You have any Lookup for a field which is nullable in a Form with a connected Model (e.g. via hasOne reference)
- You have selected an entry of the Lookup and saved.
- You then select the empty entry of that Lookup and save again

Result: Atk4/Data tries to store 0, instead of NULL. This is wrong, it has to be NULL.
Sorry can't provide a quick demo, but this should be straightforward.
Funnily, in Dropdown control it works, only in Lookup not.

**Comment by mkrecek234** [comment]
@mvorisek I added sample code in here - just set the dropdown/lookup fields in first form to empty and press save.

https://github.com/atk4/ui/blob/bug_null_zero/demos/form/form.php

**Comment by mvorisek** [comment]
> @mvorisek I added sample code in here - just set the dropdown/lookup fields in first form to empty and press save.
> 
> https://github.com/atk4/ui/blob/bug_null_zero/demos/form/form.php

thank you - repro using demo is great, I tried, but I cannot reproduce it using it.

I tried /w 1st dropdown field. When I select empty value and save, empty value is sent (correctly) to the server.

When I select `noob`, `0` is sent. When I select `pro`, `1` is sent.

This is because the values are an enumeration and expected.

When all validation rules are satisfied, the form can be saved and green Toast (that is how FUI calls this UI component) is shown in the upper right corner:

![image](https://user-images.githubusercontent.com/2228672/185236876-e548cc14-e755-40ba-82fe-4e903eb74c24.png)

this toast shows the parsed data from the client send/save. I see `null` here correctly. Thus please provide better steps to reproduce, also, I found your screencasts in the past quite helpful.

**Comment by mkrecek234** [comment]
See here the screencast - the Lookup (=Product Category Id) behaves wrongly, wheras the Dropdown class (Product_Sub_Category) behaves correctly.

https://user-images.githubusercontent.com/28671486/185292599-ef9385e9-9a44-4df4-90a0-03b1a6337518.mov

**Comment by mvorisek** [comment]
I am sorry, I tested on `develop` and not `bug_null_zero`.

**Comment by mvorisek** [comment]
![image](https://user-images.githubusercontent.com/2228672/185511879-ca918067-8f06-451c-932d-b0d221728456.png)

is sent to the server, investigating why such value is set on dropdown render
