### ISSUE TITLE
In forms, Accordion->activate(...) stopped working

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1836]
For Accordions in forms, the activate function to open Accordions on load worked until very recently (must have been introduced only max. in the last 7-10 days, as this commit still worked f8278d6934559eb8efd8f86013f39cc95bdb1475

This stopped working now, see demo - the first Accordion should open:

https://github.com/atk4/ui/blob/a120f0f4d1593a4dd10b8b3ad32668c6107d191b/demos/form/form-section-accordion.php#L66

**Comment by mvorisek** [comment]
Thank you for reporting it. Problem is present since https://github.com/atk4/ui/commit/01d39d24694e4b4f63a576d090e55e0e97aaa9e4.

The problem is removed method override https://github.com/atk4/ui/commit/01d39d24694e4b4f63a576d090e55e0e97aaa9e4#diff-08f1560acb847ce226eb00aca9621dc3412618092cd61be204df26aaf98a7ecaL62

here you can see what causes a missing test with `getOwner()` 😃
