### ISSUE TITLE
Add checkbox to table header to select/unselect all

### ISSUE THREAD

**Issue by mvorisek** [atk4/ui#1877]
When row selection is enabled, there should be "master" checkbox in the table header to select/unselect all rows.

Feature request from https://github.com/atk4/ui/issues/1727#issuecomment-1264612174.

It should probably still select the rows in the current page only.

related demo: `demos/collection/grid.php`

maybe add support for `shift` key to add support for range selection

**Comment by mhuser** [comment]
I noticed `Multiline` form control already has such a top checkbox. I will need to investigate where it is done in the code.

**Comment by mvorisek** [comment]
Isn't that only for Multiline? (not for Table/CRUD)

**Comment by mhuser** [comment]
Indeed. I could maybe just use `getHeaderCellHtml` of `Checkbox` Column type.

**Comment by mvorisek** [comment]
We need to move from vue used in Multiline to render everything via pure php to dedup the code and use standard php components purely.

**Comment by mhuser** [comment]
![image](https://user-images.githubusercontent.com/8080934/198689540-9d7be523-12e9-40ba-ac3c-2760511c250c.png)

Turned out that adding the checkbox in the header was easier than expected thanks to the existing `Checkbox` column type.
But I will still need to link it to the toggling action and that will probably be the tricky part.

#1921
