### ISSUE TITLE
CardDeck won't reload after completed UserAction with applies_to_single_record

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1910]
- You have a model with a UserAction that modifies, say the name, and has `'appliesTo' => \Atk4\Data\Model\UserAction::APPLIES_TO_SINGLE_RECORD`

- If you run that UserAction, the CardDeck should reload to reflect the changes in that record. In Crud, it works. Though, in CardDeck it won't reload the CardDeck.

Interestingly, after adding a new record, the CardDeck now updates, this did not work before.

**Comment by mvorisek** [comment]
Please always post a demo link and exact steps to reproduce like you did in https://github.com/atk4/ui/issues/1862 for example.

If such demos do not exist, you can still post a demo link with a diff of the changes needed to reproduce.

If no related demo exists, please post here a few lines of codes that can run on pure atk4/ui install, models used from atk4/ui can be present. I can then run such code and fix quickly. Otherwise I have to code such repro cases which costs time.

**Comment by mvorisek** [comment]
isn't this https://github.com/atk4/ui/issues/1848 duplicate?

it is a feature, it was never supported, but of course the behaviour should be unified/implemented

**Comment by mkrecek234** [comment]
You're right, did not see you added also the missing reload cases for edit/deletes. Closing this as duplicate of #1848.

**Comment by mkrecek234** [comment]
@mvorisek Please check branch  https://github.com/atk4/ui/tree/bug_card_deck for repro code. If you watch closely when deleting a record, you will see the first card gets a reload sign upon delete of any other card.
