### ISSUE TITLE
Cannot assign onHidden function for Modal anymore

### ISSUE THREAD

**Issue by mkrecek234** [atk4/ui#1937]
I have a modal which should trigger a callback after it is being hidden:
$this is a normal view.
```
$paymentmodal = \Atk4\Ui\Modal::addTo($this)->set(function ($v) use ($id, $model) {
                    \Atk4\Ui\Message::addTo($v, ['Test Modal.']);
                });

            // Reload view after closing of modal

            $paymentmodal->setOption('onHidden', new \Atk4\Ui\JsFunction([], [
                    (new \Atk4\Ui\JsChain('atk.modalService'))->removeModal(new \Atk4\Ui\Jquery()),
                    $this->JsReload(),
                ])
            );
```

In the recent version upon load of this view I now get this JavaScript error:
`Error: Fomantic-UI "modal.onHidden" setting cannot be customized outside atk`
jquery.min.js:2:31711

**Comment by mvorisek** [comment]
The exception saves you from state corruption, but like in FUI API we can impl. specific handler for the `onHidden` to call both (your/custom and out/atk).

**Comment by mkrecek234** [comment]
@mvorisek Can I not as before just connect to any FUI function? There are plenty of function for FUI controls where we need to connect our own Atk4 code. How can we solve this?

**Comment by mvorisek** [comment]
@mkrecek234 you can, but there are a few function that atk4/ui override to customize Fomantic-UI behaviour - this is not new, only since a few weeks we throw a JS exception properly :)

see https://github.com/atk4/ui/pull/1917

do you need to change only `onHidden` or any other callback we override? I will impl. it, but it is not easy as for every function the side effects needs to be analysed manually to "merge" the callback correctly.

**Comment by mkrecek234** [comment]
I only encountered this error when using modal onHidden. Sure there are other FUI functions (mostly onChange of values of some controls, but there are no existing overrides by atk, so no throw of exception that I encountered 👍

onHidden for Modal (or even JsModal) would be indeed very important as we have to be able to react on it to update views etc.
