### ISSUE TITLE
model->save() empties all associated form fields, even if they do not belong to the model

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#316]
Hi there, have a look at the following code and the output it produces:
```
    $middle_form->onSubmit(function($middle_form) use ($group, $lcl, $app) {
		echo 'before: '.$middle_form->fields['emails']->getValue();
		$group->save();
		echo 'after: '.$middle_form->fields['emails']->getValue();

```
The output this produces is:
![bugsaveemptiesformfields](https://user-images.githubusercontent.com/33204878/34726263-cac27976-f553-11e7-80e7-4c84d4c71cb3.png)

So, after the model associated with the form is saved, the value of the form field is gone.
I don't know if that is intended behaviour for form fields which belong to the associated model, but in my case, the field does not belong to the model. It was added to the form manually:
```

        $middle_form->addField('emails');
	$middle_form->model->getElement('emails')->never_persist = true;
```

At least in this case, the field values should stay. In my case I first need to save $group to get an ID (creating new record), so I can use this ID later in the submit function.

Best regards
Philipp

**Comment by romaninsh** [comment]
So just to confirm

 - $form->model->getElement('emails') has never_persist.
 - $form->model['emails'] is set before save.
 - $form->model['emails'] is no longer set after save.

The issue here is with a mechanism called Reloading. Essentially after saving data into the database, the record is re-loaded from database once again. When reloading, existing values are trashed. So as a result you're loosing a field which has no-persist flag, because it's not saved or loaded.

See: http://agile-data.readthedocs.io/en/develop/expressions.html?highlight=reloading#model-reloading-after-save

I do not know how to correctly address this. In your situation, simply collect the value before you save. I'll think about it though.

**Comment by PhilippGrashoff** [comment]
Hi Romans,

confirmed, you understood the case correctly. I just want to point out that the 'emails' field does not belong to the model class but is added to the form after form->setModel.
When the model is stored this field not belonging to the model looses its value.

My workaround is as you proposed, store the values before saving the model.

The nicer (and IMHO correct) solution would be if only the fields belonging to the saved model would be reloaded.

Best regards

**Comment by romaninsh** [comment]
technically it does belong to a model, because form->setModel() would call model->addField().

For the reason of having multiple persistences, I have stated this class https://github.com/atk4/ui/blob/develop/src/misc/ProxyModel.php, but it was never completed as I wasn't sure about the correct way to do it.

**Comment by PhilippGrashoff** [comment]
Adding an example in documentation should close this issue. Should be stated somewhere.

**Comment by PhilippGrashoff** [comment]
closing this.
