### ISSUE TITLE
Adding HTML5 input types

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#358]
Hi there, I would like to add HTML5 input types like color, date, email to my project.
Why not do it in ATK directly? I think the new input types are a very nice addition. Will start doing this soon and contribute if wanted.

**Comment by romaninsh** [comment]
ok.

**Comment by PhilippGrashoff** [comment]
As this requires changing the "routing" inside Form->typeToDecorator, maybe I will just create a fork which other people can test if they like.

The actual implementation of displaying various HTML5 inputs is simple:
I created new Classes in Formfield/ which just change the $inputType property of Input class:

```
<?php
class Color extends \atk4\ui\FormField\Input
{
    public $inputType = 'color';
}
```

Adding a field as` 'type' => 'color'` and changing the "routing" in Form->typeToDecorator does the job:
    ```
protected $typeToDecorator = [
		'color'	   => 'Color',
		'integer'  => 'Integer',
                ...
```

Now value validation is next but should be pretty simple too.

**Comment by romaninsh** [comment]
all you need to do is:

``` php
$model->addField('my_field', ['display'=>['Form'=>'\your\namespace\your\Fiedl']]);
```

ATK is built based on "practicality" not on "available features", which is why the priority for color picker is really low. It is very rare when you need that compared to how often you need a auto-complete field.

Date / Time selectors probably a better idea, although from my experience, the default HTML5 implementation is pretty poor and does not synergies with the selected theme. 


So if we add a new type, then the type must be respected entirely through the ATK:
 - all persistences must know how to store it
 - UI persistence must know how to read it from the form
 - form must know how to display it
 - table must know how to display it

etc.

Speaking of "integer" -  we already have this type and perhaps adding HTML5 can be helpful to limit user entry options or even bring up a proper keyboard on mobile devices. This could be a good cleanup task.

**Comment by mvorisek** [comment]
Calendar date/time/datetime control is already present, color should have some color picker integration... PR welcomed.
