### ISSUE TITLE
app method url() should have an argument indicating a regular or ajax url

### ISSUE THREAD

**Issue by roelleor** [atk4/ui#369]
Some integrations (like ibelar/atk-wordpress) need to differentiate between ajax and regular requests when creating a url. MasterCrud does a lot with regular requests. (quickSearch as well I believe)

I suggest the url interface to be:
```php
/**
     * @param bool $ajax
     * @return string
     */
    public function url($ajax = true)
```
@ibelar, do you agree?

**Comment by romaninsh** [comment]
how about url(['ajax'=>true]);

**Comment by PhilippGrashoff** [comment]
This would also help me with a problem I face:
I JSreload a lot of page parts, and when a session timeout occurs, I want to redirect to some login page if its an ajax request. If not, I want to keep the current URL and show the login form.

**Comment by ibelar** [comment]
@roelleor - not sure if this will help in WP. Problem with actual Quicksearch implementation is that it is using a Form with single input and no action to specify url, so it call the default url, which is not compatible with WP.

@romaninsh - here is the problem we are facing in WP and may be you have an idea on how to fix this.

In WP, admin page always has the same base url, i.e admin.php and the page is indicated via the 'page' argument, 
 - ex: http://site.com/wp-admin/admin.php?page=my-plugin-panel 

On the other end, for ajax request, the url must use be the same, i.e  admin-ajax.php, with specific argument like 'action'. Plus, in our case, we need to add an extra argument to define which view to load in App. 
 - Ex: http://site.com/wp-admin/admin-ajax.php?action=plugin-name&atkwp=view-to-load.

In order to make it work, when a view request an url via $view-url(), I force the use of ajax, i.e. the url with admin-ajax.php. But sometime, this cause problem and it would be good to know when to generate a regular admin url or an ajax url. Your new Wizard component is a good example of that. 

I know atk4\ui is not working the same way but to your knowledge, is there a way to differentiate when to generate a regular page url or an ajax url?

**Comment by romaninsh** [comment]
ok, i see what you mean. Here is my question - when the URL generation is passed to the api, then if you substitute name of the page based of presence of "json" argument, would that be a good work-around?

Secondly, I know that "json" argument may be no very reliable, but if the JS code invocation or rendering of jsCallback would call $app->jsUrl() for example - would that help for clarify of design and would that make it cleaner?

**Comment by roelleor** [comment]
Personally I really like the separate method jsUrl

**Comment by ibelar** [comment]
I have been testing adding and using new method App::jsUrl(). It work really good in WP and we are now able to properly generate url for regular Admin or Ajax page. Wizard and Paginator can also be use as is when using this new method. 
@romaninsh - I will send you the PR for this change. Let me know if you would like to implement it differently.  I also test it against agile demo and did not see any issue.

**Comment by DarkSide666** [comment]
Here is PR: https://github.com/atk4/ui/pull/372

**Comment by romaninsh** [comment]
I'm back from vacation, will review this and try to contribute when i am all caught up.
