### ISSUE TITLE
masterCrud - add element , hit enter, no UI feedback but adds multiple items

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#379]
When adding new item in masterCRUD, when i hit "Enter" no visual feedback is displayed (modal is not closed), yet records are added and sometimes more than one.

Clicking "save" with a button works as expected.

TODO: need to add more details.

**Comment by PhilippGrashoff** [comment]
hitting the Enter button causes this strange issue in any input field in my forms: The form is submitted by not a single reload etc. action is triggered.
p.s.: Just wanted to post this issue now :)

**Comment by romaninsh** [comment]
See #173, which was supposedly fixed by @ibelar.

**Comment by ibelar** [comment]
@romaninsh - Took a look and problem is cause by having the div element change to button in the submit form. Did that in order to have the submit button focusable ([PR#368](https://github.com/atk4/ui/pull/368)), without realizing this would bring back submitting the form twice when using one input field only. Changing the element back to div will fix problem but loose ability to have focus on button.

To re enable focus on button using a div element, we need to set tabindex=0 on that div element and manually detect user pressing a key , like below:

```
        $this->buttonSave = $this->layout->addButton(['Save', 'primary']);
        //$this->buttonSave->setElement('button');
        $this->buttonSave->setAttr('tabindex', 0);
        $this->buttonSave->on('click', $this->js()->form('submit'));
        $this->buttonSave->on('keypress', new jsExpression('if (event.keyCode === 13){$([name]).form("submit");}', ['name' => '#'.$this->name]));
```
Did some testing and it seem to work fine.

**Comment by romaninsh** [comment]
does it also work with mobile devices? Lets get this merged, I have released stable UI recently and I suspect it's also vulnerable to this bug.

**Comment by ibelar** [comment]
Can't confirm is this work in mobile device. 
I will submit PR with proposed change above.

**Comment by romaninsh** [comment]
I suspect that this is resolved now. Will re-open if it is there again.
