### ISSUE TITLE
Integrate ATK with Zend3

### ISSUE THREAD

**Issue by gartner** [atk4/ui#384]
I am (trying) to use UI inside a Zend Framework 3 application. 
I have defined a route that sends the url '/full-ui-admin' to a controller that will create a CRUD using atk4/ui.

This is working. Sort of. My code to create the CRUD is:

```php
        $app = new \atk4\ui\App('My First App');
        $app->initLayout('Admin');

        $crud = new CRUD();
        $app->add($crud);

        $model = new LinksModel($this->storage);
        $crud->setModel($model);

        // This is the Zend Framework-way of by-passing the layout and rendering.
        $response = $this->getResponse();
        return $response;
```

The result of this is a full CRUD where I can add/edit/delete records. This is all working.

But internally the atk4-appclass is building urls. Clicking the 'edit'-button for a record, the url becomes:
full-ui-admin.php?atk_admin_crud_edit=cut&__atk_callback=1&atk_admin_crud=13&json=true

A .php is added to the requested filename. It should not do that. It should - the route to this should be full-ui-admin?atk_admin_crud_edit=cut&__atk_callback=1&atk_admin_crud=13&json=true which would be a valid url here.

And even worse, the 'Dashboard'-link in the CRUD's left menu will send me to the url '/index' (it has removed the '/full-ui-admin'-part and replaced it with '/index' WITHOUT a .php-extension.

This is very confusing.

**Comment by romaninsh** [comment]
The default generation of URLs is designed for the vanilla / stand-alone case. When it comes to frameworks, each one has some quirks, which is why we suggest to extend "App" class for a particular framework and override `url()` generation methods.

In your case the correct way would be to create an App class inside add-on. Call it something like "Zend3 integration with ATK" and publish for others to use.

Here is an example for Wordpress: https://github.com/ibelar/atk-wordpress/blob/dev-master/src/AtkWpApp.php#L168

**Comment by romaninsh** [comment]
Title was: (URL-building is kind-of-buggy), changed it instead of closing ticket.

**Comment by romaninsh** [comment]
Stale. Closing. Integration is probably better now since ATK was integrated with wordpress and several other frameworks.
