### ISSUE TITLE
View->addStyle is the same as setStyle(). Why?

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#44]

**Comment by romaninsh** [comment]
the policy on add/set here is unclear. I think we should implement it "SOMEHOW" now and then create a big list of all "questions" for the version 1.1. I think some of the api in 1.0 would still be un-stable, but starting with 1.1 we should try not to change anything anymore.

Will leave this issue here for later.

**Comment by DarkSide666** [comment]
I think this can be closed. It's not "fixed", but both methods probably are used to often in projects already and it would be BC break to change something there now.
