### ISSUE TITLE
Grid should have loader while reloading

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#493]
In grid we should see Loader spinner while its content is reloading.
Reloading happens when you use Paginator or QuickSearch for example and if grid data selection is quite slow, then user don't understand what's happening because there is no visual feedback.

Related:
* https://forum.agiletoolkit.org/t/table-grid-loader/495
* also few of our support clients asked for this.

**Comment by PhilippGrashoff** [comment]
Hi,
had some of the loading spinner customizations myself. The spinner is added by "loading" class. In case a Form is submitted when using paginator/quicksearch, it can by done very simply by setting the stateContext of the form:
$form->setApiConfig(['stateContext' => 'someHTMLTagID']);

**Comment by DarkSide666** [comment]
Cool. Thanks for info.
But I believe that should be done automatically by toolkit without any additional user config.

**Comment by PhilippGrashoff** [comment]
Of course this should be part of normal Grid behaviour :)

**Comment by PhilippGrashoff** [comment]
After having a quick look into ajaxec (which should be what atkAjaxec uses if I am not mistaken), it uses SUI .api function as well. If there was the possibility to pass additional params to .api function in doExecute(), using the stateContext param should do the work?

**Comment by ibelar** [comment]
When using semantic-ui api call, the element where the call is attached get the css 'loading' class apply until the call gets complete. The css 'loading' class when combine to certain css class will display a loading indicator. 

These css classes are:

- button
- icon
- input
- segment
- form
- dropdown
- modal
- popup
- search
- shape

You may also change the stateContext of the api request setting to be applied to another element, i.e. not the element generating the call itself in order to display the loading indicator. By changing the stateContext value to another element, you are applying the 'loading' class to that element.

**Comment by PhilippGrashoff** [comment]
Well, thats a proper explanation. I think having the ability to pass additional params to .api function would be good in gerneral. In a form we have this option using Form->setApiConfig(). For View->on(), that would be great, too. Using the fourth param seems a proper place?

**Comment by romaninsh** [comment]
@PhilippGrashoff - please confirm that 'develop' branch has addressed this ticket.
