### ISSUE TITLE
File Upload inside the model? not working...

### ISSUE THREAD

**Issue by rapgithub** [atk4/ui#540]
is there a way to make work the file upload inside the model? I am using crud...

class Deal extends Model {
....
    function init() {
        parent::init();

...
$this->addField('file', ['Upload', ['accept' => ['.png', '.jpg']]]);
$img = $this->addField('file', ['UploadImg']);

this does not work either....
thanks

**Comment by PhilippGrashoff** [comment]
Try passing [new \atk4\ui\FormField\Upload()]

**Comment by romaninsh** [comment]
I'll try it tomorrow, maybe will find some sort of bug.

**Comment by DarkSide666** [comment]
Upload field is not model field type, but form field type, so you have two options here:

1. Add field in form manually and don't forget to define and implement onUpload, onDelete and onSubmit callbacks:
```
$file = $form->addField('file', new \atk4\ui\FormField_Upload([
    'accept' => ['.csv','.xls'],
    'width' => 'five',
]));
```

2. Define form field to use in data model, but still you have to manually define and implement onUpload, onDelete and onSubmit callbacks in form itself.
```
$model->addField('file', ['ui'=>['form'=>new \atk4\ui\FormField_Upload([
    'accept' => ['.csv','.xls'],
    'width' => 'five',
]) ]]);
```

Basically what you want to do is:
* onUpload - store uploaded file in some temporary folder, use setFileId() method to memorize path to that field
* onDelete - delete temporary file (garbage cleanup)
* onSubmit - do something with file. If you want to store file name in model, then do so. If you want to store file contents in model field - do so. You have to do so manually here because form will not know how you want to store this file in database/model.

**Comment by DarkSide666** [comment]
@rapgithub what's about this issue? Did you solve it?

**Comment by acicovic** [comment]
Hi, since this issue hasn't been replied to and it's old, I suggest closing it.

**Comment by DarkSide666** [comment]
agreed
