### ISSUE TITLE
Template _top tag doesn't work

### ISSUE THREAD

**Issue by DarkSide666** [atk4/ui#610]
In Template class `_top` tag related methods doesn't work.

Issue is somewhere with all these _pass array as reference_ to and from different methods. Need to change these methods to not be so complex and avoid _pass array as reference_ there.

For example, this doesn't work as we expect in Template->getTagRefList() method:
```
        if ($this->isTopTag($tag)) {
            // BUG IS HERE - THIS DOESN'T RETURN REFERENCE TO THIS->TEMPLATE !!!
            $template = &$this->template;

            return false;
        }
```

That's why we use different `_top` tag workarounds in classes like `Lister->renderView()`.

**Comment by PhilippGrashoff** [comment]
http://php.net/manual/en/language.references.arent.php
Seems like referencing a var which was passed by reference isnt possible in general, exactly what the code above tries to do.

**Comment by PhilippGrashoff** [comment]
Without reading too deep into that code:
1) The main thing getTagRef() and getTagRefList() do is to modify the second parameter which is passed by reference
2) These 2 functions are only used in Template class, nowhere else

Regarding these two facts, maybe refactoring this way would make sense:
Instead of passing $template as second param and return $this (getTagRef) | bool (getTagRefList), only pass $tag parameter and return the modified $template array instead.
This would need some minor changes in the functions calling getTagRef() | getTagRefList(), but would make these 2 functions way easier to understand as they would return their main purpose: The modified $template array.

**Comment by DarkSide666** [comment]
I thought about that and definitely agree with such solution, but not sure should they return modified template array (copy of it) or reference to that array. For example, `return $this->tempate` or `return &$this->template`

**Comment by DarkSide666** [comment]
Should be fixed by https://github.com/atk4/ui/commit/9db813a40585615f31d3f2ab13813ff0656c863f

Thanks @PhilippGrashoff for your help!
