### ISSUE TITLE
Model field type=date does not work with hidden input

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#696]
Hi there,
i am trying to use a model field type=date with a hidden input in a form. This does not work. Here is the demo code:
```
<?php

//vendor autoload...
include_once('config.php');

class HiddenDateTest extends \atk4\data\Model {
    public $table = 'date_test';

    public function init() {
        parent::init();
        $this->addFields([
            ['start_date',        'type' => 'date',       'ui' => ['form' => ['Hidden']]],
        ]);
    }
}


$app = new \atk4\ui\App();
$app->initLayout('Centered');
$form = $app->add('Form');
$form->setModel(new HiddenDateTest(new \atk4\data\Persistence_Array($_SESSION['hdt'])));
```

This causes the following exception:
![datehiddenexception](https://user-images.githubusercontent.com/33204878/57040879-0a2f2480-6c61-11e9-9300-c4d4d72602e9.png)

**Comment by DarkSide666** [comment]
It's because Form->typeToDecorator set type=date for this field and it's trying to set that $type property for Hidden form field where it of course doesn't exist.
I don't see nice way how to solve that for now.
How about using `$this->addField(['start_date', 'type' => 'date', 'ui' => ['hidden' => true]]);`. It looks that we have added this in atk4/data, but never actually used it in atk4/ui. I think this should be the proper way how to create some "not so strict Hidden field" in ui.

**Comment by romaninsh** [comment]
@PhilippGrashoff how do you envision this to work? what is the expected behaviour?

**Comment by PhilippGrashoff** [comment]
@romans, good question as dates are stored as \DateTime objects. I think if setting a hidden input to a date field what would make the most sense is to set the date to the hidden input in ISO format: Y-m-d (PHP speaking)
I will try Darksides solution (created my own workaround already).

**Comment by PhilippGrashoff** [comment]
Maybe it makes more sense to describe what I want to achieve, I am good in not finding the most straightforward solution:
I'd like to use Fomantic UI's calendar as date picker, but not as an input field which has the calendar opened on focus, but the calendar should always be visible (FUI calls it inline calendar: https://fomantic-ui.com/modules/calendar.html).

**Comment by romaninsh** [comment]
> I'd like to use Fomantic UI's calendar as date picker, but not as an input field which has the calendar opened on focus, but the calendar should always be visible

in this case create it as a view and use callback or action to do something when date is selected. 

Probably not something that can be solved with form field.

If you still need a hidden field, use a regular line:

``` php
$model->addField('dt', ['type'=>'date', 'ui'=>['Line', 'hidden'=>true]]);
```

**Comment by DarkSide666** [comment]
@romaninsh you probably mean `$model->addField('dt', ['type'=>'date', 'ui'=>['form'=>['Line']]]);` here, but that will also not work good and will throw exception because of issue in mergeSeeds() method call which will merge `['Line']` with `['Calendar', 'type'=>'date']` and get `['Line', 'type'=>'date']` seed at the end which is bad because FormField\Line class doesn't have 'type' property.

**Comment by acicovic** [comment]
@PhilippGrashoff this issue has been inactive for some months. Feel free to close this if you think it has been answered or that there's no good reason to keep it open.

**Comment by PhilippGrashoff** [comment]
Hi,
I just tried that again, and found some hacky way to deal with it:
```
            ['start_date',              'type' => 'date',       'ui' => ['form' => ['inputType' => 'Hidden']]],
```
I will close this issue.
