### ISSUE TITLE
Menu in the Demo app does not reflect my current location

### ISSUE THREAD

**Issue by gitam** [atk4/ui#72]
e.g. http://ui.agiletoolkit.org/demos/table.php

Doesn't tell where I am and what this page is about or what is header for this page

**Comment by DarkSide666** [comment]
Need to add `active` class to active menu item.
Probably that can be done somewhere in menu renderView() https://github.com/atk4/ui/blob/develop/src/Menu.php#L98

Something like:
```
if ($_SERVER['REQUEST_URI'] == $this->app->url($action)) {
    $this->item->addClass('active');
}
```

or maybe it's better to do this in Menu->addItem() method.

**Comment by romaninsh** [comment]
The active is not a problem, it's the automated detection of where you are on the page.

**Comment by acicovic** [comment]
Hi,

This thread is now old and inactive.

If we want to have this implemented then it can be submitted as a feature request (not for the demo, but as a capability in general) or added in the wishlist in order to be examined later. Perhaps it could part of the Page object in v2 if it gets implemented.

Right now as this issue stands it's more of a bug/discussion rather than a feature request so I suggest closing it or revamping it to be a feature request if it is to be implemented.

Thanks!

**Comment by acicovic** [comment]
Fixed by https://github.com/atk4/ui/pull/1120

Closing this. Feel free to reopen if needed.
