### ISSUE TITLE
#629 and #643: revert only_fields setting?

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#764]
Hi,

the PR #643 introduced that a dropdown only uses title_field and id_field for a model when selecting.
While this might be a performance tweak, it brings a problem:
If in DropDownModel::init() (or any other Model code executed during DropDown rendering) any other fields are used (e.g. in a afterLoad hook), it will cause an exception as this field is not within only_fields.

As you can hardly expect people to wrap every field in Model code in a check if the field is within only fields, I think the only way to not annoy people using ATK UI with this Exception is to not set only_fields property.

Maybe discuss in hangout, I can explain easily

**Comment by DarkSide666** [comment]
Yes we faced same issue yesterday in Saasty. Romans workaround was to add `system=>true, ui=>[editable=>true,visible=>true]` to field which we also needed to be selected besides title_field and id_field. Not good fix, but it works.

What I am still wondering is can we make fields _lazy used_ in atk4/data models. That would solve all problems everywhere. Bad thing is that I can't explain that in good details how I imagine that to work because I have no idea :)

Basically idea is that field is only selected if it's used somewhere else later on. Otherwise it's useless to select such field. If we're talking about simple fields which directly map database table, then it's ok to select all of them all the time - it's no big performance hit anyway (maybe except blobs). But if model contains expression/aggregation fields too, then it becomes very costly and useless to select them if we don't actually use them anywhere later on.

For example, we have Client and Invoice models.
```
$client->hasMany('Invoice')
    ->addField('total_amount', ['aggregate'=>'sum', 'field'=>'amount']);
```
Selecting total_amount is costly and useless to include total_amount field in select if we only need to use this model for client lookup field. On the other hand, maybe we have custom lookup field with custom template and actually want to show total_amount as part of lookup value. Then we should select this field too.

If only Model could be smart enough to _lazy use_ this total_amount field ...

**Comment by romaninsh** [comment]
We solved it by setting `system` to the fields that must be there, which in our case was the correct solution.

**Comment by PhilippGrashoff** [comment]
Regarding this issue, I think a solution would be to add another boolean property to DropDown:
`useMinimalModelFields` (or any other name that fits),
If true, it will set only_fields to title_field and id_field, if false, the model will be taken as-is.

The only thing I am unsure about is: Is default true or false?
true adds a tad of Performance but might produce an Exception, which could especially annoy new users...

**Comment by romaninsh** [comment]
@PhilippGrashoff will update doc, explaining relation between dropdowns, system fields and only_fields.

**Comment by romaninsh** [comment]
https://github.com/atk4/core/issues/108 will take care of this i hope
