### ISSUE TITLE
ATK UI 2.0 to implement Page object

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#778]
OK, so finally a page object. We can discuss if it's something that's needed.

**Comment by DarkSide666** [comment]
Not sure about this.
On one hand page is basically just a view, so no use for separate class.
On other hand - page is kind of view + url, so it maybe could take some URL related functionality away from App.

**Comment by abbadon1334** [comment]
A page concept is interesting, like Imants said Page is a View + EndPointURI, if we approach Page Concept we need to approach even Route concept and apply ACL to it, i don't know if this need to be managed internally by atk.

I don't know if it can be useful, take a look to : https://github.com/abbadon1334/atk4-fastroute
Is really fresh and i use it in a project which is in develop now.

**Comment by romaninsh** [comment]
@gowrav-vishwakarma do you have any good arguments on WHY we need page class ?

**Comment by gowrav-vishwakarma** [comment]
Hi All,

Initially, Pages was mandatory for me, but over the time I have integrated Laravel quite well with Atk and enjoying the integration but still, I see good use of pages to promote Atk as a component-based 'FRAMEWORK'. right now it is too abstract and is dependent on other frameworks (Nobody uses core PHP in good projects nowadays).

Yes, we do need Pages and Routers also.

1. New Atk UI/Data is made to be a unit of elements and to be added in any PHP framework, but as of now, I cannot add the following code in any PHP framework

`
$v = new \atk4\ui\View();
$v->js('click')->hide();
echo $v->render();
`
This will not render javascripts the way it should be. And only option remains is to add via complete APP. 

While having all APP in control why should I depend on any other framework if Atk itself can give me route and pages? 

Atk is more towards MVP and we do not have any 'P' yet. Pages can have other options that can help Routers or may be addOns or Hooks to support or hook them self in other routers or services.

I see Atk as components as well as a complete Framework and to make it complete framework Pages, Routers are good to have. 

But also in last, I am currently enjoying Laravel integration with ATK.

**Comment by abbadon1334** [comment]
@gowrav-vishwakarma if you extend the concept of page to a complete system which can have addons  that can inject new routes and new services in an ui\app, i totally agree.

We can reuse the atk4\api routing? i did something with fastroute to cover some possible of the possible cases, i think you already see this : 
https://github.com/abbadon1334/atk4-fastroute

i'm working now on a full atk project, i integrate ConfigTrait + atk4-fastroute + atk4-debugBar + login + schema ( with fluid rebuild of tables ). First of all to see if there is some problem on the whole system, second because too many times i haven't an online application to show when someone is curious about ATK and for last i want to figure out which is the best way to implement the TranslationTrait.

in few weeks i release a public alpha, just to show what i have done.

**Comment by romaninsh** [comment]
if routing in frontend and api is consistent, that would be great. 

Also - in theory we can also apply seeding ideas to the Pages - e.g. when you pass _GET argument it is assigned to page property. 

Lets discuss!

**Comment by romaninsh** [comment]
Possibly 

``` php
$button->link(LoginPage::class);
```

**Comment by acicovic** [comment]
If this gets implemented it would be nice to have API-like URLs. I had to roll back to querystring URLs because of problems with my own htaccess URLs.

**Comment by pkly** [comment]
If this is going to be a thing I'd like to request for it to be completely optional, as it's going to fight against the system I'm using already.

**Comment by acicovic** [comment]
@pkly would you like to tell us what you're using?

**Comment by pkly** [comment]
@acicovic proprietary solution for the CMS I'm writing

**Comment by acicovic** [comment]
OK

**Comment by romaninsh** [comment]
closing as there are no desire to have Page objects. They can be implemented through 3rd party router still.
