### ISSUE TITLE
Bug: CRUD, Selection Column and jsPaginator: No checkboxes for dynamically loaded records

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#837]
I have only tested this with CRUD, but this is probably a Grid issue.

When you have a CRUD with a selection column and a jsPaginator, the records which are dynamically loaded do not show a checkbox.

![image](https://user-images.githubusercontent.com/23142906/68546596-9d030580-03e0-11ea-88c9-7439cbb54ab7.png)

**Comment by ibelar** [comment]
By default and for performance reason, javascript response return when using jsPaginator is not evaluate. Since CheckBox column rely on Fomantic-ui Checkbox module they are set using javascript.

In order to have them you need to explicitly set jsPaginator to evaluate js return by the server: 
```
$g->addJsPaginator(30, ['allowJsEval' => true]);
```

Please note that doing so will reapply Checkbox to every rows within table on every scroll content load. Because TableColumn\CheckBox is not set per row basis but rather per table, like this:
```
  $("#atk_admin_grid_view_table").find(".cb_checkbox").checkbox();
```

Hope this help!

**Comment by acicovic** [comment]
Thanks, will check this out.

**Comment by acicovic** [comment]
Still had no time to test this but I will close this since a solution has been given. Thanks.
