### ISSUE TITLE
Feature: Add PHP Callback for Modal

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/ui#844]
Hi, it would be cool to have an easy way to define a PHP callback for a modal, like
```
$modal->onClose(function() {
     $modal->model->saveAsReadByUser();
});
```
This should not be too hard as FUI modal has `onClose`, in which basically just $('idOfModal').api('UrlOfCallBack') would be called.

Thinking it a bit further, of course if the behaviour matches View->on(), it would be perfect. That can either take a PHP callback, one or several jsActions, args can be passed to callback....

**Comment by ibelar** [comment]
@PhilippGrashoff Did you try?

```
$modal->addApproveAction('Yes', new \atk4\ui\jsFunction([$modal->jsReload(['action' => 'approve'])]));
```
Then clicking Yes button would reload page with argument action. This will work on Modal not jsModal.

Beside, using onHide() modal setting will be difficult because onHide is call all the time, wether user click on a button, press esc or simply click outside the modal.

**Comment by PhilippGrashoff** [comment]
damn, using jsReload is very sensible :) I will close this issue as this is a very simple way to achieve this with existing code.
