### ISSUE TITLE
Critical error new version with existing working code.

### ISSUE THREAD

**Issue by domainoverflow** [atk4/ui#963]
Hi, when I run the most current version (latest branch) against my existing base code, I get

Critical Error
atk4\core\Exception Method useSuiVue is not defined for this object

It works in 1.7.1 ( my code ). 

Any suggestions ? 

thanks !

**Comment by ibelar** [comment]
App::useSuiVue was required in v1.7 in order to use Multiline. This was to include semantic-ui-vue.js package needed to run MultinlLine form field. The package was added externally. 

As per atk4/Ui v2.0 and above, semantic-ui-vue.js is always include in atkjs-ui.js package, i.e. build internally instead. 
You should be good by simply removing the call to the method App::useSuiVue() in your existing base code for atk4/ui 2.0.

**Comment by domainoverflow** [comment]
Thank You @ibelar .. I found the App::useSueVue invoke call at atk4/invoice ( thanks btw  https://github.com/atk4/invoice/issues/13 ) and commented it out. Everything is back to normal. Thanks for your help !!
