### ISSUE TITLE
[BUG] CRUD does not save values with field names containing dots

### ISSUE THREAD

**Issue by georgehristov** [atk4/ui#965]
MySQL supports field names having dots in the name.

When declaring model with fields containing dots in the name all works fine. CRUD displays the 'add' form and accepts the values but they are not stored in database.

No errors are thrown.

**Comment by PhilippGrashoff** [comment]
I had a similar issue with `-` in the HTML id of the form. In that case the reason was that the JS serializer didnt recognize `-`. Maybe its the same reason with the dot.

**Comment by PhilippGrashoff** [comment]
https://github.com/atk4/ui/issues/495

**Comment by georgehristov** [comment]
Thanks @PhilippGrashoff !
Replacing the dots with underscore solved the issue immediately but maybe good idea to think of a general more flexible solution like adding the custom JS serializer settings to atk?

**Comment by ibelar** [comment]
@georgehristov - Form input with '.' in their name are not serialized by default in FormSerailize object plugin. So having this input in your form: `<input name='field.test'>` will be ignored in form send request. 

If your need is to accept this type of input name, then you can set up the FormSerialize plugin to accept them using the following via an external js file. 
````
$.extend(FormSerializer.patterns,{
  validate:/^[a-z][a-z0-9_.]*(?:\[(?:\d*|[a-z0-9_.]+)\])*$/i,
  key:      /[a-z0-9_.]+|(?=\[\])/gi,
  named:    /^[a-z0-9_.]+$/i
});
````
However, note that even if this will send the input name "field.test" with your form request.  It will be transformed into $_POST['field_test'] because PHP will change dot or space character to an underscore character automatically. This means that you may need to implement your own post-processing to convert it back to dot char.

Hope this helps!

**Comment by georgehristov** [comment]
@ibelar thanks a lot for explanation. I will stick with underscores, the rest of symbols appear exotic and require customization I'd like to avoid.
